services:
    # Event subscribers and listeners
    rk_download_module.entity_lifecycle_listener:
        class: RK\DownLoadModule\Listener\EntityLifecycleListener
        arguments:
            - "@service_container"
            - "@event_dispatcher"
            - "@logger"
        tags: ['doctrine.event_subscriber']
    
    rk_download_module.kernel_listener:
        class: RK\DownLoadModule\Listener\KernelListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.installer_listener:
        class: RK\DownLoadModule\Listener\InstallerListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.moduledispatch_listener:
        class: RK\DownLoadModule\Listener\ModuleDispatchListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.mailer_listener:
        class: RK\DownLoadModule\Listener\MailerListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.theme_listener:
        class: RK\DownLoadModule\Listener\ThemeListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.userlogin_listener:
        class: RK\DownLoadModule\Listener\UserLoginListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.userlogout_listener:
        class: RK\DownLoadModule\Listener\UserLogoutListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.user_listener:
        class: RK\DownLoadModule\Listener\UserListener
        arguments:
            - "@translator.default"
            - "@rk_download_module.entity_factory"
            - "@zikula_users_module.current_user"
            - "@logger"
        tags: ['kernel.event_subscriber']
    
    rk_download_module.userregistration_listener:
        class: RK\DownLoadModule\Listener\UserRegistrationListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.users_listener:
        class: RK\DownLoadModule\Listener\UsersListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.group_listener:
        class: RK\DownLoadModule\Listener\GroupListener
        tags: ['kernel.event_subscriber']
    
    rk_download_module.thirdparty_listener:
        class: RK\DownLoadModule\Listener\ThirdPartyListener
        arguments:
            - "@filesystem"
            - "@request_stack"
        tags: ['kernel.event_subscriber']
    
    rk_download_module.workflow_events_listener:
        class: RK\DownLoadModule\Listener\WorkflowEventsListener
        arguments:
            - "@zikula_permissions_module.api.permission"
        tags: ['kernel.event_subscriber']
    
